<script lang="ts">
  let code = '';
  function createRoom() { code = 'DUEL-' + Math.random().toString(36).slice(2, 8).toUpperCase(); }
</script>
<svelte:head><title>Nuevo duelo | Duel Assistant</title></svelte:head>

<div class="new-page"><a class="back" href="/">← Volver al inicio</a><div class="new-grid"><section><p class="eyebrow">Paso 01 / Preparar mesa</p><h1>Abre una sala<br /><em>para jugar.</em></h1><p class="lead">Crea un duelo privado, comparte el codigo y lleva el control de cada turno.</p></section><section class="setup-panel"><div class="panel-head"><span>Configuracion del duelo</span><span class="step">01 / 02</span></div><label>Nombre de la sala<input placeholder="Duelo de viernes" /></label><label>Oponente (opcional)<input placeholder="Buscar por usuario..." /></label><div class="mode"><span class="selected">Privado<small>Solo entra quien tenga el codigo</small></span><span>Publico<small>Aparece en la lista de duelos</small></span></div><button on:click={createRoom}>Crear sala <span>→</span></button>{#if code}<div class="room-code"><small>Codigo para compartir</small><strong>{code}</strong><button class="copy" on:click={() => navigator.clipboard?.writeText(code)}>Copiar codigo</button><a href="/duel/demo">Entrar a la sala de prueba →</a></div>{/if}</section></div></div>
<style>
.new-page{min-height:100vh;padding:30px clamp(24px,7vw,100px);background:linear-gradient(125deg,#f4f4ed,#e3ebe0)}.back{font:11px 'DM Mono',monospace;color:#637064}.new-grid{max-width:1100px;margin:clamp(70px,12vw,145px) auto;display:grid;grid-template-columns:1fr 1fr;gap:clamp(45px,10vw,150px);align-items:center}.new-page h1{font-size:clamp(52px,7vw,90px);line-height:.92;letter-spacing:-.075em;margin:15px 0}.new-page h1 em{color:#d9573b;font-style:normal}.eyebrow{color:#d9573b;font:11px 'DM Mono',monospace;text-transform:uppercase;letter-spacing:.08em}.lead{max-width:380px;color:#637064;line-height:1.6}.setup-panel{background:#fffdf7;padding:28px;box-shadow:12px 18px 40px #82918122}.panel-head{display:flex;justify-content:space-between;border-bottom:1px solid #e0e5dc;padding-bottom:20px;margin-bottom:25px;font:12px 'DM Mono',monospace;text-transform:uppercase}.step{color:#d9573b}.setup-panel label{display:grid;gap:8px;margin-bottom:18px;color:#637064;font:11px 'DM Mono',monospace;text-transform:uppercase}.setup-panel input{border:1px solid #d5ddd2;padding:14px;background:#f7f8f3;font:15px 'Space Grotesk',sans-serif}.mode{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:25px 0}.mode span{padding:14px;background:#f1f3ed;color:#637064;font-size:13px}.mode .selected{background:#17211b;color:#fff}.mode small{display:block;margin-top:5px;color:#9aa89c;font-size:10px}.setup-panel button{width:100%;border:0;padding:15px;background:#d9573b;color:white;text-align:left;display:flex;justify-content:space-between;cursor:pointer}.room-code{margin-top:20px;padding:20px;background:#f3e4d0;text-align:center}.room-code small{display:block;color:#8f6f4e;font:10px 'DM Mono',monospace;text-transform:uppercase}.room-code strong{display:block;margin:7px;font:700 30px 'DM Mono',monospace;letter-spacing:.08em}.room-code .copy{display:inline-block;width:auto;background:none;color:#d9573b;padding:0;font:11px 'DM Mono',monospace}.room-code a{display:block;margin-top:17px;color:#17211b;font-size:13px}@media(max-width:720px){.new-grid{grid-template-columns:1fr;margin:80px auto}.new-page h1{font-size:57px}}
</style>
